Sprint 12
PJ1nho/ImageFeed pull request #5
Opened 2023-03-21 20:31 UTC by PJ1nho

2023-03-22 22:00 UTC, IBDesignable requested changes

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/Auth/OAuth2Service.swift
В сервисах не принято мешать презентационную логику, поэтому давай этот код отсюда удалим и перенесем рядом с контроллером, который его вызывает

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/Auth/OAuth2Service.swift
далее по коду надо будет еще поправить такие места

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +    }
рекомендую вынести этот код в отдельный сервис, Статику у контроллеров не принято заводить

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    @IBAction func likeButtonClicked() {
private - здесь и далее по коду надо все перепроверить

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListService.swift
> +                dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
Создание форматера дорогостоящая операция – следует создать форматтер единожды для всех запросов как указано в задании

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListService.swift
> +                let photos = data.map {return Photo(id: $0.id, size: .init(width: $0.width, height: $0.height), createdAt: dateFormatter.date(from: $0.createdAt), welcomeDescription: $0.description,
тут очень длинная строка, которую не прочитать. 

Предлагаю сделать extension у Photo Result с методом конвертации. 
func convertToViewModel() -> Photo 

ТОгда этот код будет проще выглядеть: data.map { $0.convertToViewModel() }

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListService.swift
> +            }.resume()
Не получится написать один раз запрос, но ответ и реквест собирать в зависимости от входного параметра? 

Мне кажется ты бы здесь много дублирования убрал одним махом

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    var imageListCell = ImagesListCell()
это тут зачем? таблица создает, хранит, переиспользует ячейки. Самостоятельные ссылки приведут к ошибкам. Надо убрать этот код и решить задачу как-то иначе

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        }))
Почему бы не использовать подход с алерт презентером из предыдущего модуля? Так бы лишний код смог убрать

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +    var logOutButton = UIButton()
прайваты пропущены

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +            return
ретерн лишний здесь

2023-03-22 22:00 UTC, IBDesignable commented on ImageFeed/Profile/ProfileViewController.swift
> +        }))
```suggestion
        alert.addAction(UIAlertAction(title: "Нет", style: .default, handler: { _ in }))
```

2023-03-24 20:52 UTC, ABashkirova requested changes

2023-03-24 20:52 UTC, ABashkirova commented on ImageFeed/URLSessionExtension.swift
>              }
вот в этом ветвлении не возвращается ошибка. В итоге пользователь может застрять на каком-то из запросов и думать что приложение зависло. 

На скрине зависшее приложение: виден только профиль, распечатан print success из сервиса ImageListService:
<img width="1749" alt="Снимок экрана 2023-03-24 в 22 35 43" src="https://user-images.githubusercontent.com/20269264/227637582-3bb3e4fa-94cd-4516-93a8-307c79549ef4.png">

Ошибка заключается в том, что при попытке получить данные из профиля, декодер завершается с ошибкой и возвращает опциональный responseData:

<img width="1044" alt="Снимок экрана 2023-03-24 в 22 46 14" src="https://user-images.githubusercontent.com/20269264/227636944-e3cff242-33d3-45ef-8fda-627a923164ac.png">

Эта ошибка говорит о том, что структура, которую ты пытаешься получить для профиля не удовлетворяет
ответу.
В поле lastname пришел null. Нужно поправить структуру данных, полагая что там могут быть некоторые поля опциональные. Чтобы узнать какие - можно поэкспериментировать в Unspalsh. 

<img width="994" alt="Снимок экрана 2023-03-24 в 22 50 25" src="https://user-images.githubusercontent.com/20269264/227637225-55fea7db-17ae-4b4d-9756-b37468746551.png">

2023-03-24 20:54 UTC, IBDesignable requested changes

2023-03-24 20:54 UTC, IBDesignable commented on ImageFeed/ImagesList/DateFormatterService.swift
> +    }
Здесь ты упаковал форматтеры в сервис – это хорошее начало. Но что тут стоит заметить: ты используешь вычислимые свойства – каждый раз когда ты обратишься DateFormatterService. shared. responseDateFormatter – будет выполняться тело комплишена. 

Вычислимые свойства немного похожи на функции, так как они ничего не хранят, но всегда что-то возвращают. Как и здесь – будет создано и возвращено новое значение. 

Поэтому таким образом ты не избавляешься от предыдущей ошибки. 


Но к счастью мы можем поправить это так: 

1) сделать свойства константами, инициализацию провести в ините:

```swift
let responseDateFormatter: DateFormatter
let imageDateFormatter: DateFormatter

private init() {
   responseDateFormatter = DateFormatter() 
   .... 
}
```
 
либо же, использовав отложенную иницализацию через лейзи свойство:

```swift
lazy var responseDateFormatter: DateFormatter = {
       let dateFormatter = DateFormatter()
        ...
        return dateFormatter
}()
```

оба эти варианта решают задачу, и в твоем случае будут одинаковы по временизатратам. Выбирай любой.

2023-03-24 20:54 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        }
здесь избыточно, потому что делегат таблицы и так работает на главном потоке

2023-03-24 20:54 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            }
а вот здесь уже нет – мы не знаем как сторонняя библиотека поступает с комплишенами, здесь все верно

2023-03-24 20:54 UTC, IBDesignable commented on ImageFeed/URLSessionExtension.swift
> +                }
Я уже писала что UIBlockingProgressHUD не должен попадать в методы сервисов и URLSession, эту работу стоит делать рядом с презентационной логикой. 

Я понимаю что это может быть трудно сейчас переписать – но так ты привыкаешь писать грамотный код. 
Смешивание слоев логики не должно происходить :)

2023-03-24 20:54 UTC, IBDesignable commented on ImageFeed/URLSessionExtension.swift
>              }
вот в этом ветвлении не возвращается ошибка. В итоге пользователь может застрять на каком-то из запросов и думать что приложение зависло. 

На скрине зависшее приложение: виден только профиль, распечатан print success из сервиса ImageListService:

<img width="1749" alt="Снимок экрана 2023-03-24 в 22 35 43" src="https://user-images.githubusercontent.com/121577115/227637788-f9864db7-af6d-4e8b-a989-305c018e01f7.png">

Ошибка заключается в том, что при попытке получить данные из профиля, декодер завершается с ошибкой и возвращает опциональный responseData:
<img width="1044" alt="Снимок экрана 2023-03-24 в 22 46 14" src="https://user-images.githubusercontent.com/121577115/227637834-2a7d4983-9377-4da8-9676-b6c795cb756b.png">

Эта ошибка говорит о том, что структура, которую ты пытаешься получить для профиля не удовлетворяет
ответу.
В поле lastname пришел null. Нужно поправить структуру данных, полагая что там могут быть некоторые поля опциональные. Чтобы узнать какие - можно поэкспериментировать в Unspalsh. 
<img width="1012" alt="Снимок экрана 2023-03-24 в 22 54 19" src="https://user-images.githubusercontent.com/121577115/227637900-597047cb-60fb-4f4c-bc37-83d1838656c7.png">

2023-03-27 17:52 UTC, IBDesignable commented
Привет! Все еще не исправлена ошибка с профилем. 


Попробуй из такого Json получить структуру ProfileResult. Я все еще не могу проверить задачу без починки этой ошибки (смотри комментарии в пулреквесте выше)

```json
{
  "id": "7otKKchRTAk",
  "updated_at": "2023-03-27T17:44:48Z",
  "username": "ypios",
  "name": "Yandex",
  "first_name": "Yandex",
  "last_name": null,
  "twitter_username": null,
  "portfolio_url": null,
  "bio": null,
  "location": null,
  "links": {
    "self": "https://api.unsplash.com/users/ypios",
    "html": "https://unsplash.com/@ypios",
    "photos": "https://api.unsplash.com/users/ypios/photos",
    "likes": "https://api.unsplash.com/users/ypios/likes",
    "portfolio": "https://api.unsplash.com/users/ypios/portfolio",
    "following": "https://api.unsplash.com/users/ypios/following",
    "followers": "https://api.unsplash.com/users/ypios/followers"
  },
  "profile_image": {
    "small": "https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
    "medium": "https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
    "large": "https://images.unsplash.com/profile-1678707963239-a1234aeaac5fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128"
  },
  "instagram_username": null,
  "total_collections": 0,
  "total_likes": 10,
  "total_photos": 0,
  "accepted_tos": false,
  "for_hire": false,
  "social": {
    "instagram_username": null,
    "portfolio_url": null,
    "twitter_username": null,
    "paypal_email": null
  },
  "followed_by_user": false,
  "photos": [],
  "badge": null,
  "tags": {
    "custom": [],
    "aggregated": []
  },
  "followers_count": 0,
  "following_count": 0,
  "allow_messages": true,
  "numeric_id": 12349835,
  "downloads": 0,
  "meta": {
    "index": false
  },
  "uid": "7otKKchRTAk",
  "confirmed": true,
  "uploads_remaining": 10,
  "unlimited_uploads": false,
  "email": "ypios@pm.me",
  "dmca_verification": "unverified",
  "unread_in_app_notifications": false,
  "unread_highlight_notifications": false
}
```

2023-03-30 06:32 UTC, ABashkirova commented on ImageFeed/Profile/ProfileResult.swift
>      let bio: String?
👍🏻

2023-03-30 06:54 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +        var request = URLRequest(url: url)
Попробуй убрать дублирующую часть вот так:

```swift
if isLike {
    request = URLRequest.makeRequest(path: "photos/\(photoId)/like", httpMethod: "POST")
    if let token = OAuth2TokenStorage().token {
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
    } 
}
else {
    request = URLRequest.makeRequest(path: "photos/\(photoId)/like", httpMethod: "DELETE")
    if let token = OAuth2TokenStorage().token {
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
    }
}

let task = URLSession.shared.dataTask(with: request) ...
```

2023-03-30 06:54 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private var photoNames: [String] = Array(0..<20).map{ "\($0)" }
Эта строчка больше не нужна, как и моковые фотографии - можно убрать

2023-03-30 06:57 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    }
установка через ikeButton.imageView?.image  будет работать нестабильно. Лучше использовать специальный метод `likeButton.setImage(UIImage(named: "likeActive"), for: .normal)`

иначе будем наблюдать такое поведение:
![RocketSim_Recording_iPhone_11_2023-03-30_09 43 47](https://user-images.githubusercontent.com/20269264/228754106-73366239-8c12-4e64-9c63-fc4cdff0c24a.gif)

2023-03-30 07:07 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    }
Здесь еще можно дополнительно очищать стейт перед переиспользованием ячейки: сбросить предыдущую картинку, кнопку лайка привести в дефолтное состояние

2023-03-30 07:46 UTC, merged